baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[outputs]
    home = ["HTML", "RSS", "JSON"] # å¿…é¡»ç”Ÿæˆ JSON ç´¢å¼•æ–‡ä»¶

[params]
    showToc = true
    TocOpen = false # æ˜¯å¦é»˜è®¤å±•å¼€
    [params.profileMode]
        enabled = true
        title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ tooram"
        subtitle = "è¿™é‡Œè®°å½•æˆ‘ä¸æˆ‘çš„ç¬”è®°"
        imageUrl = "img/avatar.jpg" # æ”¾ç½®åœ¨ static/img/ ç›®å½•ä¸‹
        [[menu.main]]
            name = "ğŸ” æœç´¢"
            url = "search"
            weight = 10 # æ•°å­—è¶Šå°è¶Šé å·¦
        [[params.profileMode.buttons]]
            name = "ç¬”è®°"
            url = "posts"
        [[params.profileMode.buttons]]
            name = "å…³äºæˆ‘"
            url = "about"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/tooram"